USE word_tracker;

ALTER TABLE plans
ADD COLUMN IF NOT EXISTS is_archived BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS status VARCHAR(50) DEFAULT 'active',
ADD COLUMN IF NOT EXISTS color_code VARCHAR(20) DEFAULT '#3b82f6';
